# Generated by Django 3.2.5 on 2021-07-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persian_news_classification.reference')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persian_news_classification.word')),
            ],
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persian_news_classification.reference')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persian_news_classification.word')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titr_string', models.TextField()),
                ('titr_string_code', models.TextField()),
                ('titr_words', models.JSONField()),
                ('titr_words_code', models.JSONField()),
                ('titr_words_without_stopword', models.JSONField()),
                ('titr_words_without_stopword_code', models.JSONField()),
                ('content_string', models.TextField()),
                ('content_string_code', models.TextField()),
                ('content_words', models.JSONField()),
                ('content_words_code', models.JSONField()),
                ('content_words_without_stopword', models.JSONField()),
                ('content_words_without_stopword_code', models.JSONField()),
                ('vector', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persian_news_classification.category')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persian_news_classification.reference')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persian_news_classification.reference'),
        ),
    ]
