# Generated by Django 3.2.5 on 2021-07-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persian_news_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
