# Generated by Django 3.2.5 on 2021-07-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persian_news_classification', '0002_alter_word_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symbol',
        ),
    ]
