# Generated by Django 3.2.5 on 2021-08-01 14:08

from django.db import migrations, models
import persian_news_classification.models


class Migration(migrations.Migration):

    dependencies = [
        ('persian_news_classification', '0003_delete_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('ftype', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to=persian_news_classification.models.get_upload_to)),
            ],
        ),
    ]
