# Generated by Django 3.2.5 on 2021-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persian_news_classification', '0005_auto_20210802_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
