# Generated by Django 3.2.5 on 2021-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persian_news_classification', '0006_reference_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='load_complate_flag',
            field=models.BooleanField(default=False),
        ),
    ]
