# Generated by Django 3.2.5 on 2021-08-16 09:20

from django.db import migrations, models
import extra_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=128)),
                ('file', models.FileField()),
                ('load_complate', models.BooleanField(default=False)),
                ('which_row', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
