# Generated by Django 3.2.5 on 2021-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_settings', '0002_auto_20210816_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='file_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='fileinfo',
            old_name='file_path',
            new_name='fpath',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='fformat',
            field=models.CharField(choices=[('xlsx', 'xlsx'), ('csv', 'csv'), ('json', 'json'), ('pkl', 'pkl')], default=11, max_length=8),
            preserve_default=False,
        ),
    ]
