# Generated by Django 3.2.5 on 2021-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_settings', '0003_auto_20210816_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='ftype',
            field=models.CharField(choices=[('stopwords_list', 'stopwords_list'), ('symbols_list', 'symbols_list'), ('news', 'news'), ('documents', 'documents')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
