# Generated by Django 3.2.5 on 2021-08-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_settings', '0004_fileinfo_ftype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='load_complate',
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='which_row',
        ),
    ]
