# Generated by Django 3.2.5 on 2021-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_settings', '0006_auto_20210824_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='fname',
            field=models.CharField(max_length=512),
        ),
    ]
