# Generated by Django 3.2.5 on 2021-08-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('_number_of_subcategories', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=32)),
                ('_number_of_repetitions', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Titr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField()),
                ('words', models.ManyToManyField(to='statistical_pnc.Word')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticalWordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_docs_frequency', models.JSONField(blank=True, null=True)),
                ('docs_frequency_mean', models.FloatField(blank=True, null=True)),
                ('docs_frequency_stdev', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.category')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.word')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.category')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.context')),
                ('keywords', models.ManyToManyField(related_name='sn_keywords', to='statistical_pnc.Word')),
                ('titr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.titr')),
                ('words_tokenize', models.ManyToManyField(related_name='sn_words', to='statistical_pnc.Word')),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='words',
            field=models.ManyToManyField(to='statistical_pnc.Word'),
        ),
    ]
