# Generated by Django 3.2.5 on 2021-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='words',
            field=models.ManyToManyField(related_name='sn_words', to='statistical_pnc.Word'),
        ),
        migrations.AlterField(
            model_name='news',
            name='words_tokenize',
            field=models.ManyToManyField(related_name='sn_words_tokenize', to='statistical_pnc.Word'),
        ),
    ]
