# Generated by Django 3.2.5 on 2021-08-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0003_auto_20210808_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('load_symbols_list', models.BooleanField(default=False)),
                ('load_stopwords_list', models.BooleanField(default=False)),
                ('load_complate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.reference')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.word')),
            ],
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.reference')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.word')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.reference'),
            preserve_default=False,
        ),
    ]
