# Generated by Django 3.2.5 on 2021-08-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0004_auto_20210810_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.reference'),
            preserve_default=False,
        ),
    ]
