# Generated by Django 3.2.5 on 2021-08-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0006_auto_20210814_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.reference'),
        ),
        migrations.AlterField(
            model_name='news',
            name='titr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.titr'),
        ),
    ]
