# Generated by Django 3.2.5 on 2021-08-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0007_auto_20210814_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='keywords',
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.news')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.word')),
            ],
        ),
    ]
