# Generated by Django 3.2.5 on 2021-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0009_news_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
