# Generated by Django 3.2.5 on 2021-08-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0010_category__vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='_vector',
        ),
    ]
