# Generated by Django 3.2.5 on 2021-08-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0011_remove_category__vector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='vector',
            new_name='_vector',
        ),
    ]
