# Generated by Django 3.2.5 on 2021-08-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0012_rename_vector_news__vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='_hash_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='_hash_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='titr',
            name='_hash_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='_hash_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
