# Generated by Django 3.2.5 on 2021-09-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0013_auto_20210830_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopword',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistical_pnc.reference'),
        ),
    ]
