# Generated by Django 3.2.5 on 2021-09-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_pnc', '0014_alter_stopword_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='_number_of_subcategories',
            new_name='number_of_subcategories',
        ),
    ]
